In [3]:
import pandas as pd

In [4]:
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Supermarket_Practice_Data.xlsx")

##Detect Missing Values

In [5]:
# Check all missing values in the entire dataset
data.isna()

,Invoice_ID,Sale_Date,Product,Category,City,Quantity,Unit_Price,Discount,Revenue,Cost,Payment_Method,Customer_Type,Data_Quality_Issues
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,False,False,False,False,False,False,False,False,False,False,False,False,False
118,False,False,False,False,False,False,False,False,False,False,False,False,True
119,False,False,False,False,False,False,False,False,False,False,False,False,True
120,False,False,False,False,False,False,False,False,False,False,False,False,True
121,False,False,False,False,False,False,False,False,False,False,False,False,True

In [6]:
# Check missing values only in the city column
data["City"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
117    False
118    False
119    False
120    False
121    False
Name: City, Length: 122, dtype: bool

In [7]:
# Count the number of missing values in each column
Missing_Data = data.isnull().sum()

Missing_Data

Invoice_ID              0
Sale_Date               0
Product                 1
Category                0
City                    1
Quantity                1
Unit_Price              1
Discount                0
Revenue                 1
Cost                    0
Payment_Method          0
Customer_Type           1
Data_Quality_Issues    82
dtype: int64

In [8]:
# Count all missing values in the entire dataset
Total_Missing = data.isnull().sum().sum()

Total_Missing

np.int64(88)

In [9]:
# Calculate the percentage of missing values in each column
Missing_Percentage = data.isna().mean() * 100

Missing_Percentage

Invoice_ID              0.000000
Sale_Date               0.000000
Product                 0.819672
Category                0.000000
City                    0.819672
Quantity                0.819672
Unit_Price              0.819672
Discount                0.000000
Revenue                 0.819672
Cost                    0.000000
Payment_Method          0.000000
Customer_Type           0.819672
Data_Quality_Issues    67.213115
dtype: float64

In [10]:
# Calculate the proportion of missing values
data.isna().mean()

Invoice_ID             0.000000
Sale_Date              0.000000
Product                0.008197
Category               0.000000
City                   0.008197
Quantity               0.008197
Unit_Price             0.008197
Discount               0.000000
Revenue                0.008197
Cost                   0.000000
Payment_Method         0.000000
Customer_Type          0.008197
Data_Quality_Issues    0.672131
dtype: float64

In [11]:
# Hel qiimaha ugu badan ee ku soo noqnoqda Gender
data["City"].mode()

0    Mogadishu
Name: City, dtype: object

In [12]:
# Hel Mode-ka oo keliya, adigoo qaadanaya value-ga ugu horreeya
mode = data["City"].mode()[0]

mode

'Mogadishu'

In [13]:
# Tiri inta jeer ee value kasta ku soo noqdo Gender
data["City"].value_counts()

City
Mogadishu    38
Garowe       31
Kismayo      28
Hargeisa     23
Mogadisho     1
Name: count, dtype: int64

In [14]:
# Hel Mode-ka Gender
mode = data["City"].mode()[0]

# Tiri inta jeer ee Mode-ku soo noqday
count = data["City"].value_counts()[mode]

# Soo bandhig natiijada
print("Column:", "City")
print("Mode:", mode)
print("Count:", count)

Column: City
Mode: Mogadishu
Count: 38

In [15]:
# Hel Mode-ka column kasta
modes = data.mode().iloc[0]

# Tiri inta jeer ee Mode-ka column kasta soo noqday
mode_counts = {}

for column in data.columns:
    mode_counts[column] = data[column].value_counts().get(modes[column], 0)

mode_counts

{'Invoice_ID': np.int64(2),
 'Sale_Date': np.int64(3),
 'Product': np.int64(17),
 'Category': np.int64(27),
 'City': np.int64(38),
 'Quantity': np.int64(21),
 'Unit_Price': np.int64(3),
 'Discount': np.int64(32),
 'Revenue': np.int64(2),
 'Cost': np.int64(2),
 'Payment_Method': np.int64(31),
 'Customer_Type': np.int64(47),
 'Data_Quality_Issues': np.int64(29)}

In [16]:
# Soo saar rows-ka leh ugu yaraan hal missing value
data[data.isna().any(axis=1)]

,Invoice_ID,Sale_Date,Product,Category,City,Quantity,Unit_Price,Discount,Revenue,Cost,Payment_Method,Customer_Type,Data_Quality_Issues
2,INV-1003,2026-01-21,Bread,Bakery,Mogadishu,8.0,0.89,0.02,6.98,4.42,Bank Transfer,Member,NaN
3,INV-1004,2026-06-19,Apple 1kg,Produce,Kismayo,5.0,2.42,0.00,12.10,8.77,Bank Transfer,New,NaN
4,INV-1005,2026-02-20,Rice 5kg,Grocery,Garowe,4.0,6.69,0.10,24.08,19.09,Cash,Regular,NaN
5,INV-1006,2026-01-09,NaN,Dairy,Hargeisa,2.0,3.30,0.10,5.94,4.84,Cash,Member,Missing Product
6,INV-1007,2026-01-08,Chicken 1kg,Meat,Garowe,4.0,5.86,0.05,22.27,17.39,Card,Member,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,INV-1117,2026-05-19,Milk 1L,Dairy,Garowe,2.0,1.31,0.02,2.57,1.93,Bank Transfer,Regular,NaN
118,INV-1119,2026-01-17,Orange Juice 1L,Beverages,Mogadishu,2.0,1.94,0.05,3.69,2.93,Card,New,NaN
119,INV-1120,2026-03-10,Orange Juice 1L,Beverages,Hargeisa,6.0,2.11,0.02,12.41,8.12,Bank Transfer,Member,NaN
120,INV-1013,2026-02-10,Orange Juice 1L,Beverages,Kismayo,3.0,2.30,0.05,6.55,4.38,Card,Regular,NaN
121,INV-1046,2026-06-22,Orange Juice 1L,Beverages,Kismayo,5.0,1.93,0.05,9.17,6.95,Cash,Member,NaN

In [17]:
# Samee dataset cusub oo aan ku tijaabino dropna()
data_clean = data.dropna()

In [18]:
# Isbarbar dhig tirada rows-ka dataset-ka asalka ah iyo kan la nadiifiyay
print("Before:", data.shape[0])
print("After:", data_clean.shape[0])

Before: 122
After: 34

In [19]:
# Hel celceliska Cost-ka, adigoo iska indhatiraya missing values
Cost_mean = data["Cost"].mean()

Cost_mean

np.float64(8.141639344262297)

In [20]:
# Hel Median-ka Cost-ka
Cost_median = data["Cost"].median()

Cost_median

4.945

In [21]:
# Tirada Cost values-ka maqan
data["Cost"].isna().sum()

np.int64(0)

In [22]:
# Tiri missing values-ka column kasta
data.isna().sum()

Invoice_ID              0
Sale_Date               0
Product                 1
Category                0
City                    1
Quantity                1
Unit_Price              1
Discount                0
Revenue                 1
Cost                    0
Payment_Method          0
Customer_Type           1
Data_Quality_Issues    82
dtype: int64

##Filling Numerical Data

In [23]:
# Hel celceliska Quantity-ka, adigoo iska indhatiraya missing value
Quantity_mean = data["Quantity"].mean()

Quantity_mean

np.float64(4.115702479338843)

In [24]:
# Hel median-ka Quantity, iyadoo missing values-ka la iska indhatirayo
Quantity_median = data["Quantity"].median()

Quantity_median

4.0

In [26]:
# Buuxi Quantity-da maqan adigoo isticmaalaya mean-ka Quantity
data["Quantity"] = data["Quantity"].fillna(Quantity_mean)
print(data["Quantity"])

0      4.0
1      3.0
2      8.0
3      5.0
4      4.0
      ...
117    3.0
118    2.0
119    6.0
120    3.0
121    5.0
Name: Quantity, Length: 122, dtype: float64

In [27]:
# Hubi inta missing value ee hadda ku jirta Quantity
data["Quantity"].isna().sum()

np.int64(0)

In [28]:
# Hel mean-ka Unit_Price, iyadoo missing value-ka la iska indhatirayo
Unit_Price_mean = data["Unit_Price"].mean()

Unit_Price_mean

np.float64(2.5289256198347108)

In [29]:
# Hel median-ka Unit_Price
Unit_Price_median = data["Unit_Price"].median()

Unit_Price_median

2.11

In [30]:
# Buuxi Unit_Price-da maqan adigoo isticmaalaya mean-ka
data["Unit_Price"] = data["Unit_Price"].fillna(Unit_Price_mean)

In [31]:
# Hubi inta missing value ee hadda ku jirta Unit_Price
data["Unit_Price"].isna().sum()

np.int64(0)

## fill Categorical Data

In [32]:
# Hel mode-ka Product
Product_mode = data["Product"].mode()[0]

Product_mode

'Orange Juice 1L'

In [33]:
# Buuxi Product-ka maqan adigoo isticmaalaya mode-ka Product
data["Product"] = data["Product"].fillna(Product_mode)

In [34]:
data["Product"].isna().sum()

np.int64(0)

In [35]:
# Hel magaalada ugu badan (mode) ee City
City_mode = data["City"].mode()[0]

City_mode

'Mogadishu'

In [36]:
# Buuxi City-ga maqan adigoo isticmaalaya mode-ka City
data["City"] = data["City"].fillna(City_mode)

In [37]:
# Hubi inta missing value ee hadda ku jirta City
data["City"].isna().sum()

np.int64(0)

In [38]:
# Hel Customer_Type-ka ugu badan (mode)
Customer_Type_mode = data["Customer_Type"].mode()[0]

Customer_Type_mode

'Regular'

In [39]:
# Buuxi Customer_Type-ka maqan adigoo isticmaalaya mode-ka
data["Customer_Type"] = data["Customer_Type"].fillna(Customer_Type_mode)

In [40]:
# Hubi inta missing value ee hadda ku jirta Customer_Type
data["Customer_Type"].isna().sum()

np.int64(0)

In [41]:
# Hubi rows-ka duplicate-ka ah
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
117    False
118    False
119    False
120     True
121     True
Length: 122, dtype: bool

In [42]:
# Tiri inta duplicate row ee dataset-ka ku jirta
data.duplicated().sum()

np.int64(2)

In [43]:
# Soo bandhig rows-ka duplicate-ka ah oo keliya
data[data.duplicated()]

,Invoice_ID,Sale_Date,Product,Category,City,Quantity,Unit_Price,Discount,Revenue,Cost,Payment_Method,Customer_Type,Data_Quality_Issues
120,INV-1013,2026-02-10,Orange Juice 1L,Beverages,Kismayo,3.0,2.30,0.05,6.55,4.38,Card,Regular,NaN
121,INV-1046,2026-06-22,Orange Juice 1L,Beverages,Kismayo,5.0,1.93,0.05,9.17,6.95,Cash,Member,NaN

In [44]:
# Soo bandhig dhammaan rows-ka ku jira kooxaha duplicate-ka ah
data[data.duplicated(keep=False)]

,Invoice_ID,Sale_Date,Product,Category,City,Quantity,Unit_Price,Discount,Revenue,Cost,Payment_Method,Customer_Type,Data_Quality_Issues
12,INV-1013,2026-02-10,Orange Juice 1L,Beverages,Kismayo,3.0,2.30,0.05,6.55,4.38,Card,Regular,NaN
45,INV-1046,2026-06-22,Orange Juice 1L,Beverages,Kismayo,5.0,1.93,0.05,9.17,6.95,Cash,Member,NaN
120,INV-1013,2026-02-10,Orange Juice 1L,Beverages,Kismayo,3.0,2.30,0.05,6.55,4.38,Card,Regular,NaN
121,INV-1046,2026-06-22,Orange Juice 1L,Beverages,Kismayo,5.0,1.93,0.05,9.17,6.95,Cash,Member,NaN

In [45]:
# Ka saar duplicate rows oo ku kaydi dataset cusub
data_no_duplicates = data.drop_duplicates()

# Eeg tirada rows iyo columns kadib marka duplicates la saaro
data_no_duplicates.shape

(120, 13)