In [ ]:
## day 2 practice

In [ ]:
import pandas as pd

##load excel data

In [ ]:
data=pd.read_excel("/content/drive/MyDrive/Colab Notebooks/22_Insurance_Data_Analytics_Project.xlsx",header=2)

In [ ]:
data.columns

Index(['Row_No', 'Policy_ID', 'Policy_Date', 'Policy_Type', 'Customer_Age',
       'Premium', 'Claim_Amount', 'Claim_Status', 'Data_Quality_Notes',
       'Policy_Year', 'Policy_Month', 'Age_Group', 'Claim_Ratio',
       'Priority_Flag', 'Policy_ID_Prefix', 'Type_Upper', 'Days_Open'],
      dtype='object')

##I selected the Gender column from the DataFrame. The result is a Pandas Series.

In [ ]:
# Select one column from the DataFrame
data['Customer_Age']

0      73
1      31
2      37
3      31
4      28
       ..
273    46
274    47
275    30
276    20
277    32
Name: Customer_Age, Length: 278, dtype: int64

##Interpretation:
Code-kan wuxuu DataFrame-ka data ka soo saaraya laba column:

Claim_Status&
Age_Group

In [ ]:
# To select multiple columns, use a list of column names
# The outer brackets select data from the DataFrame
# The inner brackets create a list of column names
data[['Age_Group','Claim_Status']]

           Age_Group Claim_Status
0       Senior (60+)     No Claim
1      Adult (25-40)      Pending
2      Adult (25-40)      Pending
3      Adult (25-40)     Approved
4      Adult (25-40)     No Claim
..               ...          ...
273  Mid-Age (41-60)     No Claim
274  Mid-Age (41-60)     No Claim
275    Adult (25-40)     No Claim
276    Young (18-24)     No Claim
277    Adult (25-40)     No Claim

[278 rows x 2 columns]

##Interpretation:
Code-kan wuxuu dooranayaa row-ga label-kiisu yahay 0.

👉 loc[] waxaa loo isticmaalaa in lagu doorto xog iyadoo la adeegsanayo labels

In [ ]:
# loc[] is used to select rows using row labels
# Here we are selecting the row with label 0
data.loc[0]

Row_No                                  1
Policy_ID                        POL00110
Policy_Date           2025-10-09 00:00:00
Policy_Type                          Life
Customer_Age                           73
Premium                             313.1
Claim_Amount                          0.0
Claim_Status                     No Claim
Data_Quality_Notes           Date imputed
Policy_Year                          2025
Policy_Month                     Oct-2025
Age_Group                    Senior (60+)
Claim_Ratio                           0.0
Priority_Flag                      Normal
Policy_ID_Prefix                      POL
Type_Upper                           LIFE
Days_Open                             241
Name: 0, dtype: object

##Interpretation:
Code-kan wuxuu dooranayaa rows badan, laga bilaabo 0 ilaa 5.

👉 loc[] wuxuu ku darayaa ending label-ka, sidaas darteed waxaa la helayaa:

0, 1, 2, 3, 4, 5

In [ ]:
# Select several rows using row labels
# Here we select rows from label 0 through label 5
data.loc[0:5]

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
0,1,POL00110,2025-10-09,Life,73,313.10,0.00,No Claim,Date imputed,2025,Oct-2025,Senior (60+),0.00,Normal,POL,LIFE,241
1,2,POL00229,2026-04-24,Motor,31,323.64,1646.56,Pending,Claim amount imputed,2026,Apr-2026,Adult (25-40),5.09,Needs Review,POL,MOTOR,100
2,3,POL00098,2025-02-13,Life,37,333.82,4200.03,Pending,OK,2025,Feb-2025,Adult (25-40),12.58,Needs Review,POL,LIFE,411
3,4,POL00220,2026-03-11,Property,31,449.01,1953.01,Approved,OK,2026,Mar-2026,Adult (25-40),4.35,Normal,POL,PROPERTY,132
4,5,POL00088,2025-12-11,Health,28,378.73,0.00,No Claim,OK,2025,Dec-2025,Adult (25-40),0.00,Normal,POL,HEALTH,196
5,6,POL00112,2025-11-16,Life,43,528.80,3093.69,Approved,OK,2025,Nov-2025,Mid-Age (41-60),5.85,High-Value Approved,POL,LIFE,214

select rows and column with lock

In [ ]:
  ## selected row 10-20  columns:
data.loc[10:20,['Claim_Status','Premium']]

   Claim_Status  Premium
10     No Claim   351.89
11     No Claim   565.56
12     No Claim   299.62
13     No Claim   489.34
14     Rejected   459.88
15      Pending   457.20
16      Pending   400.34
17     No Claim   225.58
18     Rejected   316.81
19     Approved   406.44
20     No Claim   387.98

##Interpretation:
iloc[] wuxuu xogta ku dooranayaa position/nambar.

In [ ]:
# iloc[] selects rows and columns using integer positions
# This selects positions 0, 1, and 2
# The ending position 3 is not included
data.iloc[0:3]

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
0,1,POL00110,2025-10-09,Life,73,313.10,0.00,No Claim,Date imputed,2025,Oct-2025,Senior (60+),0.00,Normal,POL,LIFE,241
1,2,POL00229,2026-04-24,Motor,31,323.64,1646.56,Pending,Claim amount imputed,2026,Apr-2026,Adult (25-40),5.09,Needs Review,POL,MOTOR,100
2,3,POL00098,2025-02-13,Life,37,333.82,4200.03,Pending,OK,2025,Feb-2025,Adult (25-40),12.58,Needs Review,POL,LIFE,411

select rows and column usin iloc 1:10 rows 3:5 column

In [ ]:
data.iloc[1:10,3:5]

  Policy_Type  Customer_Age
1       Motor            31
2        Life            37
3    Property            31
4      Health            28
5        Life            43
6        Life            53
7      Health            60
8       Motor            23
9    Property            62

# loc[] uses labels
# iloc[] uses integer positions
# loc[] can use column names
# iloc[] uses column positions
# loc[] generally includes the ending label
# iloc[] excludes the ending position

# Filtering means selecting only observations
# that satisfy a specific condition
##Interpretation:
Filtering waxaa loola jeedaa inaan xogta ka soo saarno kaliya rows-ka buuxinaya shuruud gaar ah.

 Numerical Conditions

In [ ]:
# Select customer whose Premium is less than 110
# < means less than
data[data['Premium'] < 110]

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
22,23,POL00223,2025-03-28,Travel,21,106.30,0.00,No Claim,Premium imputed,2025,Mar-2025,Young (18-24),0.00,Normal,POL,TRAVEL,380
48,49,POL00253,2025-11-02,Travel,47,86.60,0.00,No Claim,OK,2025,Nov-2025,Mid-Age (41-60),0.00,Normal,POL,TRAVEL,224
89,90,POL00003,2026-04-24,Travel,19,83.21,0.00,No Claim,OK,2026,Apr-2026,Young (18-24),0.00,Normal,POL,TRAVEL,100
93,94,POL00283,2025-03-24,Travel,55,106.30,0.00,No Claim,Premium imputed,2025,Mar-2025,Mid-Age (41-60),0.00,Normal,POL,TRAVEL,384
116,117,POL00047,2025-05-12,Travel,19,90.91,849.98,Unknown,Claim_Status imputed,2025,May-2025,Young (18-24),9.35,Needs Review,POL,TRAVEL,349
121,122,POL00216,2025-11-05,Travel,25,104.91,0.00,No Claim,OK,2025,Nov-2025,Adult (25-40),0.00,Normal,POL,TRAVEL,222
136,137,POL00150,2025-04-04,Travel,59,97.75,669.29,Rejected,OK,2025,Apr-2025,Mid-Age (41-60),6.85,Normal,POL,TRAVEL,375
140,141,POL00006,2025-07-03,Travel,58,98.24,675.10,Rejected,OK,2025,Jul-2025,Mid-Age (41-60),6.87,Normal,POL,TRAVEL,311
179,180,POL00225,2025-01-31,Travel,30,101.66,0.00,No Claim,OK,2025,Jan-2025,Adult (25-40),0.00,Normal,POL,TRAVEL,420
198,199,POL00189,2025-08-20,Travel,80,107.94,0.00,No Claim,OK,2025,Aug-2025,Senior (60+),0.00,Normal,POL,TRAVEL,277
219,220,POL00042,2025-10-30,Travel,30,107.14,0.00,No Claim,OK,2025,Oct-2025,Adult (25-40),0.00,Normal,POL,TRAVEL,226
224,225,POL00151,2025-10-09,Travel,62,82.95,392.84,Rejected,Date imputed,2025,Oct-2025,Senior (60+),4.74,Normal,POL,TRAVEL,241
257,258,POL00288,2026-03-22,Travel,57,107.21,730.73,Approved,Claim amount imputed,2026,Mar-2026,Mid-Age (41-60),6.82,Normal,POL,TRAVEL,124

##Categorical Conditions

In [ ]:
# Select only customar whose Policy_Type is Travel
# == means equal to
data[data['Policy_Type'] == "Travel"]

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
22,23,POL00223,2025-03-28,Travel,21,106.30,0.00,No Claim,Premium imputed,2025,Mar-2025,Young (18-24),0.00,Normal,POL,TRAVEL,380
40,41,POL00232,2026-07-17,Travel,54,124.69,0.00,No Claim,OK,2026,Jul-2026,Mid-Age (41-60),0.00,Normal,POL,TRAVEL,40
48,49,POL00253,2025-11-02,Travel,47,86.60,0.00,No Claim,OK,2025,Nov-2025,Mid-Age (41-60),0.00,Normal,POL,TRAVEL,224
89,90,POL00003,2026-04-24,Travel,19,83.21,0.00,No Claim,OK,2026,Apr-2026,Young (18-24),0.00,Normal,POL,TRAVEL,100
93,94,POL00283,2025-03-24,Travel,55,106.30,0.00,No Claim,Premium imputed,2025,Mar-2025,Mid-Age (41-60),0.00,Normal,POL,TRAVEL,384
111,112,POL00165,2025-09-15,Travel,33,113.63,894.28,Rejected,OK,2025,Sep-2025,Adult (25-40),7.87,Normal,POL,TRAVEL,259
116,117,POL00047,2025-05-12,Travel,19,90.91,849.98,Unknown,Claim_Status imputed,2025,May-2025,Young (18-24),9.35,Needs Review,POL,TRAVEL,349
121,122,POL00216,2025-11-05,Travel,25,104.91,0.00,No Claim,OK,2025,Nov-2025,Adult (25-40),0.00,Normal,POL,TRAVEL,222
136,137,POL00150,2025-04-04,Travel,59,97.75,669.29,Rejected,OK,2025,Apr-2025,Mid-Age (41-60),6.85,Normal,POL,TRAVEL,375
140,141,POL00006,2025-07-03,Travel,58,98.24,675.10,Rejected,OK,2025,Jul-2025,Mid-Age (41-60),6.87,Normal,POL,TRAVEL,311
145,146,POL00278,2025-10-09,Travel,78,119.44,1032.98,Approved,Date imputed,2025,Oct-2025,Senior (60+),8.65,Normal,POL,TRAVEL,241
179,180,POL00225,2025-01-31,Travel,30,101.66,0.00,No Claim,OK,2025,Jan-2025,Adult (25-40),0.00,Normal,POL,TRAVEL,420
188,189,POL00236,2025-10-09,Travel,47,122.10,730.73,Pending,Claim amount imputed; Date imputed,2025,Oct-2025,Mid-Age (41-60),5.98,Needs Review,POL,TRAVEL,241
198,199,POL00189,2025-08-20,Travel,80,107.94,0.00,No Claim,OK,2025,Aug-2025,Senior (60+),0.00,Normal,POL,TRAVEL,277
210,211,POL00198,2026-03-27,Travel,79,119.92,604.95,Unknown,Claim_Status imputed,2026,Mar-2026,Senior (60+),5.04,Needs Review,POL,TRAVEL,120
219,220,POL00042,2025-10-30,Travel,30,107.14,0.00,No Claim,OK,2025,Oct-2025,Adult (25-40),0.00,Normal,POL,TRAVEL,226
224,225,POL00151,2025-10-09,Travel,62,82.95,392.84,Rejected,Date imputed,2025,Oct-2025,Senior (60+),4.74,Normal,POL,TRAVEL,241
239,240,POL00142,2025-10-09,Travel,37,120.35,726.42,Approved,Date imputed,2025,Oct-2025,Adult (25-40),6.04,Normal,POL,TRAVEL,241
241,242,POL00105,2025-05-21,Travel,40,124.72,730.73,Approved,Claim amount imputed,2025,May-2025,Adult (25-40),5.86,Normal,POL,TRAVEL,342
257,258,POL00288,2026-03-22,Travel,57,107.21,730.73,Approved,Claim amount imputed,2026,Mar-2026,Mid-Age (41-60),6.82,Normal,POL,TRAVEL,124

## Filtering Multiple Categories
Interpretation:
Halkan waxaan rabnaa inaan soo saarno policies-ka Claim_Status-koodu yahay Open ama Closed.

data['Claim_Status'] → waxaan dooranaynaa column-ka Claim_Status
.isin() → wuxuu hubinayaa haddii value-ku ku jiro list-ka

In [ ]:
# Select rows where Claim_Status is either Open or Closed
# isin() checks whether a value belongs to a list of values
data[data['Claim_Status'].isin(['Approved', 'Rejected'])]

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
3,4,POL00220,2026-03-11,Property,31,449.01,1953.01,Approved,OK,2026,Mar-2026,Adult (25-40),4.35,Normal,POL,PROPERTY,132
5,6,POL00112,2025-11-16,Life,43,528.80,3093.69,Approved,OK,2025,Nov-2025,Mid-Age (41-60),5.85,High-Value Approved,POL,LIFE,214
6,7,POL00167,2025-11-25,Life,53,354.41,391.32,Approved,OK,2025,Nov-2025,Mid-Age (41-60),1.10,Normal,POL,LIFE,208
14,15,POL00238,2025-02-02,Life,62,459.88,2930.07,Rejected,Claim amount imputed,2025,Feb-2025,Senior (60+),6.37,Normal,POL,LIFE,419
18,19,POL00013,2025-12-24,Health,71,316.81,665.90,Rejected,OK,2025,Dec-2025,Senior (60+),2.10,Normal,POL,HEALTH,187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,261,POL00287,2025-08-02,Health,24,341.31,1903.29,Approved,OK,2025,Aug-2025,Young (18-24),5.58,Normal,POL,HEALTH,289
262,263,POL00271,2025-09-05,Health,62,316.28,2676.48,Approved,OK,2025,Sep-2025,Senior (60+),8.46,Normal,POL,HEALTH,265
266,267,POL00256,2025-05-26,Health,37,368.48,1534.08,Rejected,Policy_Type imputed,2025,May-2025,Adult (25-40),4.16,Normal,POL,HEALTH,339
270,271,POL00169,2025-09-19,Health,68,436.45,2970.52,Approved,OK,2025,Sep-2025,Senior (60+),6.81,Normal,POL,HEALTH,255
271,272,POL00260,2025-03-28,Life,26,504.32,1353.33,Approved,OK,2025,Mar-2025,Adult (25-40),2.68,Normal,POL,LIFE,380

In [ ]:
# Select customers younger than 30
# AND whose claim status is Open
# & means AND
data[(data['Premium'] < 400) & (data['Policy_Type'] == 'Property')]

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
9,10,POL00066,2025-10-09,Property,62,395.53,4924.33,Pending,OK,2025,Oct-2025,Senior (60+),12.45,Needs Review,POL,PROPERTY,241
44,45,POL00210,2025-07-28,Property,43,367.06,2244.89,Rejected,OK,2025,Jul-2025,Mid-Age (41-60),6.12,Normal,POL,PROPERTY,294
54,55,POL00039,2026-05-27,Property,68,389.30,3463.86,Pending,OK,2026,May-2026,Senior (60+),8.90,Needs Review,POL,PROPERTY,77
64,65,POL00247,2025-06-14,Property,66,339.61,0.00,No Claim,OK,2025,Jun-2025,Senior (60+),0.00,Normal,POL,PROPERTY,324
105,106,POL00274,2025-08-09,Property,60,345.58,3094.19,Approved,OK,2025,Aug-2025,Mid-Age (41-60),8.95,High-Value Approved,POL,PROPERTY,284
106,107,POL00221,2026-05-28,Property,51,387.51,708.18,Pending,OK,2026,May-2026,Mid-Age (41-60),1.83,Needs Review,POL,PROPERTY,76
110,111,POL00245,2026-01-05,Property,30,389.49,0.00,No Claim,OK,2026,Jan-2026,Adult (25-40),0.00,Normal,POL,PROPERTY,179
119,120,POL00002,2025-02-08,Property,37,378.53,0.00,Unknown,Claim_Status imputed,2025,Feb-2025,Adult (25-40),0.00,Needs Review,POL,PROPERTY,414
123,124,POL00073,2025-12-11,Property,39,368.65,0.00,No Claim,OK,2025,Dec-2025,Adult (25-40),0.00,Normal,POL,PROPERTY,196
128,129,POL00137,2026-03-26,Property,64,378.39,0.00,No Claim,OK,2026,Mar-2026,Senior (60+),0.00,Normal,POL,PROPERTY,121
132,133,POL00106,2025-10-13,Property,53,381.10,1006.99,Approved,OK,2025,Oct-2025,Mid-Age (41-60),2.64,Normal,POL,PROPERTY,239
159,160,POL00005,2025-08-05,Property,40,336.95,0.00,No Claim,OK,2025,Aug-2025,Adult (25-40),0.00,Normal,POL,PROPERTY,288
165,166,POL00084,2025-07-23,Property,44,362.72,0.00,No Claim,OK,2025,Jul-2025,Mid-Age (41-60),0.00,Normal,POL,PROPERTY,297
183,184,POL00051,2026-01-30,Property,75,371.54,0.00,No Claim,OK,2026,Jan-2026,Senior (60+),0.00,Normal,POL,PROPERTY,160
231,232,POL00279,2025-01-30,Property,22,374.71,0.00,No Claim,OK,2025,Jan-2025,Young (18-24),0.00,Normal,POL,PROPERTY,421
238,239,POL00163,2025-09-10,Property,45,380.64,0.00,No Claim,OK,2025,Sep-2025,Mid-Age (41-60),0.00,Normal,POL,PROPERTY,262
251,252,POL00007,2025-03-19,Property,75,377.49,2880.16,Pending,Claim amount imputed,2025,Mar-2025,Senior (60+),7.63,Needs Review,POL,PROPERTY,387
268,269,POL00233,2025-07-20,Property,50,376.36,1097.74,Pending,OK,2025,Jul-2025,Mid-Age (41-60),2.92,Needs Review,POL,PROPERTY,299

##Sorting Data

Interpretation:
Halkan waxaan xogta ku kala saaraynaynaa da'da customer-ka.

data.sort_values() → waxaa loo isticmaalaa sorting.
'Customer_Age' → waa column-ka aan ku kala saaraynayno.
Default ahaan → wuxuu isticmaalaa ascending order.

In [ ]:
# Sort the data according to the Customer_Age column
# By default, Pandas sorts in ascending order
data.sort_values('Customer_Age')

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
125,126,POL00214,2025-09-10,Motor,18,331.71,448.98,Approved,OK,2025,Sep-2025,Young (18-24),1.35,Normal,POL,MOTOR,262
127,128,POL00188,2026-04-06,Health,18,341.88,542.70,Pending,Premium imputed,2026,Apr-2026,Young (18-24),1.59,Needs Review,POL,HEALTH,114
173,174,POL00187,2025-11-03,Health,18,389.95,1630.84,Approved,OK,2025,Nov-2025,Young (18-24),4.18,Normal,POL,HEALTH,224
172,173,POL00104,2025-01-05,Life,18,449.77,0.00,No Claim,OK,2025,Jan-2025,Young (18-24),0.00,Normal,POL,LIFE,439
78,79,POL00280,2026-06-22,Health,18,358.91,0.00,No Claim,OK,2026,Jun-2026,Young (18-24),0.00,Normal,POL,HEALTH,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,31,POL00075,2025-04-28,Life,79,443.35,2545.82,Rejected,OK,2025,Apr-2025,Senior (60+),5.74,Normal,POL,LIFE,359
210,211,POL00198,2026-03-27,Travel,79,119.92,604.95,Unknown,Claim_Status imputed,2026,Mar-2026,Senior (60+),5.04,Needs Review,POL,TRAVEL,120
101,102,POL00029,2025-07-28,Property,80,538.52,2781.42,Unknown,Claim_Status imputed,2025,Jul-2025,Senior (60+),5.16,Needs Review,POL,PROPERTY,294
198,199,POL00189,2025-08-20,Travel,80,107.94,0.00,No Claim,OK,2025,Aug-2025,Senior (60+),0.00,Normal,POL,TRAVEL,277
208,209,POL00201,2025-10-09,Property,80,435.62,1148.09,Rejected,OK,2025,Oct-2025,Senior (60+),2.64,Normal,POL,PROPERTY,241

In [ ]:
# Sort Customer_Age from the smallest value to the largest value
# ascending=True means ascending order
data.sort_values('Customer_Age', ascending=True)

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
198,199,POL00189,2025-08-20,Travel,80,107.94,0.00,No Claim,OK,2025,Aug-2025,Senior (60+),0.00,Normal,POL,TRAVEL,277
101,102,POL00029,2025-07-28,Property,80,538.52,2781.42,Unknown,Claim_Status imputed,2025,Jul-2025,Senior (60+),5.16,Needs Review,POL,PROPERTY,294
208,209,POL00201,2025-10-09,Property,80,435.62,1148.09,Rejected,OK,2025,Oct-2025,Senior (60+),2.64,Normal,POL,PROPERTY,241
30,31,POL00075,2025-04-28,Life,79,443.35,2545.82,Rejected,OK,2025,Apr-2025,Senior (60+),5.74,Normal,POL,LIFE,359
210,211,POL00198,2026-03-27,Travel,79,119.92,604.95,Unknown,Claim_Status imputed,2026,Mar-2026,Senior (60+),5.04,Needs Review,POL,TRAVEL,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,173,POL00104,2025-01-05,Life,18,449.77,0.00,No Claim,OK,2025,Jan-2025,Young (18-24),0.00,Normal,POL,LIFE,439
143,144,POL00023,2025-04-23,Life,18,387.77,3835.86,Approved,OK,2025,Apr-2025,Young (18-24),9.89,High-Value Approved,POL,LIFE,362
78,79,POL00280,2026-06-22,Health,18,358.91,0.00,No Claim,OK,2026,Jun-2026,Young (18-24),0.00,Normal,POL,HEALTH,59
127,128,POL00188,2026-04-06,Health,18,341.88,542.70,Pending,Premium imputed,2026,Apr-2026,Young (18-24),1.59,Needs Review,POL,HEALTH,114
125,126,POL00214,2025-09-10,Motor,18,331.71,448.98,Approved,OK,2025,Sep-2025,Young (18-24),1.35,Normal,POL,MOTOR,262

In [ ]:
# Sort Customer_Age from the largest value to the smallest value
# ascending=False means descending order
data.sort_values('Customer_Age', ascending=False)

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
198,199,POL00189,2025-08-20,Travel,80,107.94,0.00,No Claim,OK,2025,Aug-2025,Senior (60+),0.00,Normal,POL,TRAVEL,277
101,102,POL00029,2025-07-28,Property,80,538.52,2781.42,Unknown,Claim_Status imputed,2025,Jul-2025,Senior (60+),5.16,Needs Review,POL,PROPERTY,294
208,209,POL00201,2025-10-09,Property,80,435.62,1148.09,Rejected,OK,2025,Oct-2025,Senior (60+),2.64,Normal,POL,PROPERTY,241
30,31,POL00075,2025-04-28,Life,79,443.35,2545.82,Rejected,OK,2025,Apr-2025,Senior (60+),5.74,Normal,POL,LIFE,359
210,211,POL00198,2026-03-27,Travel,79,119.92,604.95,Unknown,Claim_Status imputed,2026,Mar-2026,Senior (60+),5.04,Needs Review,POL,TRAVEL,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,173,POL00104,2025-01-05,Life,18,449.77,0.00,No Claim,OK,2025,Jan-2025,Young (18-24),0.00,Normal,POL,LIFE,439
143,144,POL00023,2025-04-23,Life,18,387.77,3835.86,Approved,OK,2025,Apr-2025,Young (18-24),9.89,High-Value Approved,POL,LIFE,362
78,79,POL00280,2026-06-22,Health,18,358.91,0.00,No Claim,OK,2026,Jun-2026,Young (18-24),0.00,Normal,POL,HEALTH,59
127,128,POL00188,2026-04-06,Health,18,341.88,542.70,Pending,Premium imputed,2026,Apr-2026,Young (18-24),1.59,Needs Review,POL,HEALTH,114
125,126,POL00214,2025-09-10,Motor,18,331.71,448.98,Approved,OK,2025,Sep-2025,Young (18-24),1.35,Normal,POL,MOTOR,262

In [ ]:
# Sort the data first by Policy_Type
# Then sort by Claim_Status
data.sort_values(by=['Policy_Type', 'Claim_Status'])

,Row_No,Policy_ID,Policy_Date,Policy_Type,Customer_Age,Premium,Claim_Amount,Claim_Status,Data_Quality_Notes,Policy_Year,Policy_Month,Age_Group,Claim_Ratio,Priority_Flag,Policy_ID_Prefix,Type_Upper,Days_Open
29,30,POL00192,2026-07-10,Health,32,406.97,2363.82,Approved,OK,2026,Jul-2026,Adult (25-40),5.81,Normal,POL,HEALTH,45
52,53,POL00001,2025-07-16,Health,40,341.88,3273.23,Approved,Premium imputed,2025,Jul-2025,Adult (25-40),9.57,High-Value Approved,POL,HEALTH,302
56,57,POL00174,2025-12-18,Health,43,328.07,2881.08,Approved,OK,2025,Dec-2025,Mid-Age (41-60),8.78,Normal,POL,HEALTH,191
57,58,POL00055,2025-09-24,Health,48,378.18,1792.67,Approved,OK,2025,Sep-2025,Mid-Age (41-60),4.74,Normal,POL,HEALTH,252
61,62,POL00226,2025-07-09,Health,28,347.04,1963.68,Approved,OK,2025,Jul-2025,Adult (25-40),5.66,Normal,POL,HEALTH,307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,137,POL00150,2025-04-04,Travel,59,97.75,669.29,Rejected,OK,2025,Apr-2025,Mid-Age (41-60),6.85,Normal,POL,TRAVEL,375
140,141,POL00006,2025-07-03,Travel,58,98.24,675.10,Rejected,OK,2025,Jul-2025,Mid-Age (41-60),6.87,Normal,POL,TRAVEL,311
224,225,POL00151,2025-10-09,Travel,62,82.95,392.84,Rejected,Date imputed,2025,Oct-2025,Senior (60+),4.74,Normal,POL,TRAVEL,241
116,117,POL00047,2025-05-12,Travel,19,90.91,849.98,Unknown,Claim_Status imputed,2025,May-2025,Young (18-24),9.35,Needs Review,POL,TRAVEL,349
210,211,POL00198,2026-03-27,Travel,79,119.92,604.95,Unknown,Claim_Status imputed,2026,Mar-2026,Senior (60+),5.04,Needs Review,POL,TRAVEL,120